before:
  hooks:
    - go mod tidy
builds:
  - id: livekit-cli
    env:
      - CGO_ENABLED=0
    main: ./cmd/livekit-cli
    binary: livekit-cli
    goarch:
      - amd64
      - arm64
    goos:
      - linux
      - windows
      - darwin
archives:
  - format_overrides:
      - goos: windows
        format: zip
    replacements:
      darwin: mac
    files:
      - LICENSE
nfpms:
  - package_name: livekit-cli
    vendor: LiveKit
    homepage: https://livekit.io
    description: |-
      CLI for LiveKit.
    license: Apache 2.0
    maintainer: "LiveKit Team <hello@livekit.io>"
    formats:
      - deb
      - rpm
release:
  github:
    owner: livekit
    name: livekit
  draft: true
  prerelease: auto
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
gomod:
  proxy: true
  mod: mod
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
