//go:build console

// Package webrtc provides WebRTC audio processing module (APM) source compiled via CGo.
// This package and its sub-packages contain the extracted WebRTC APM C++ source.
// Import this package (typically via blank import) to link all WebRTC APM object files.
package webrtc

import (
	_ "github.com/livekit/livekit-cli/v2/pkg/apm/webrtc/api"
	_ "github.com/livekit/livekit-cli/v2/pkg/apm/webrtc/api/audio"
	_ "github.com/livekit/livekit-cli/v2/pkg/apm/webrtc/api/environment"
	_ "github.com/livekit/livekit-cli/v2/pkg/apm/webrtc/api/numerics"
	_ "github.com/livekit/livekit-cli/v2/pkg/apm/webrtc/api/task_queue"
	_ "github.com/livekit/livekit-cli/v2/pkg/apm/webrtc/api/transport"
	_ "github.com/livekit/livekit-cli/v2/pkg/apm/webrtc/api/units"
	_ "github.com/livekit/livekit-cli/v2/pkg/apm/webrtc/common_audio"
	_ "github.com/livekit/livekit-cli/v2/pkg/apm/webrtc/common_audio/resampler"
	_ "github.com/livekit/livekit-cli/v2/pkg/apm/webrtc/common_audio/signal_processing"
	_ "github.com/livekit/livekit-cli/v2/pkg/apm/webrtc/common_audio/third_party/ooura/fft_size_128"
	_ "github.com/livekit/livekit-cli/v2/pkg/apm/webrtc/common_audio/third_party/ooura/fft_size_256"
	_ "github.com/livekit/livekit-cli/v2/pkg/apm/webrtc/common_audio/third_party/spl_sqrt_floor"
	_ "github.com/livekit/livekit-cli/v2/pkg/apm/webrtc/common_audio/vad"
	_ "github.com/livekit/livekit-cli/v2/pkg/apm/webrtc/modules/audio_coding/codecs/isac/main/source"
	_ "github.com/livekit/livekit-cli/v2/pkg/apm/webrtc/modules/audio_processing"
	_ "github.com/livekit/livekit-cli/v2/pkg/apm/webrtc/modules/audio_processing/aec3"
	_ "github.com/livekit/livekit-cli/v2/pkg/apm/webrtc/modules/audio_processing/aec_dump"
	_ "github.com/livekit/livekit-cli/v2/pkg/apm/webrtc/modules/audio_processing/aecm"
	_ "github.com/livekit/livekit-cli/v2/pkg/apm/webrtc/modules/audio_processing/agc"
	_ "github.com/livekit/livekit-cli/v2/pkg/apm/webrtc/modules/audio_processing/agc/legacy"
	_ "github.com/livekit/livekit-cli/v2/pkg/apm/webrtc/modules/audio_processing/agc2"
	_ "github.com/livekit/livekit-cli/v2/pkg/apm/webrtc/modules/audio_processing/agc2/rnn_vad"
	_ "github.com/livekit/livekit-cli/v2/pkg/apm/webrtc/modules/audio_processing/capture_levels_adjuster"
	_ "github.com/livekit/livekit-cli/v2/pkg/apm/webrtc/modules/audio_processing/echo_detector"
	_ "github.com/livekit/livekit-cli/v2/pkg/apm/webrtc/modules/audio_processing/include"
	_ "github.com/livekit/livekit-cli/v2/pkg/apm/webrtc/modules/audio_processing/logging"
	_ "github.com/livekit/livekit-cli/v2/pkg/apm/webrtc/modules/audio_processing/ns"
	_ "github.com/livekit/livekit-cli/v2/pkg/apm/webrtc/modules/audio_processing/utility"
	_ "github.com/livekit/livekit-cli/v2/pkg/apm/webrtc/modules/audio_processing/vad"
	_ "github.com/livekit/livekit-cli/v2/pkg/apm/webrtc/rtc_base"
	_ "github.com/livekit/livekit-cli/v2/pkg/apm/webrtc/rtc_base/containers"
	_ "github.com/livekit/livekit-cli/v2/pkg/apm/webrtc/rtc_base/experiments"
	_ "github.com/livekit/livekit-cli/v2/pkg/apm/webrtc/rtc_base/memory"
	_ "github.com/livekit/livekit-cli/v2/pkg/apm/webrtc/rtc_base/numerics"
	_ "github.com/livekit/livekit-cli/v2/pkg/apm/webrtc/rtc_base/strings"
	_ "github.com/livekit/livekit-cli/v2/pkg/apm/webrtc/rtc_base/synchronization"
	_ "github.com/livekit/livekit-cli/v2/pkg/apm/webrtc/rtc_base/system"
	_ "github.com/livekit/livekit-cli/v2/pkg/apm/webrtc/system_wrappers/source"
	_ "github.com/livekit/livekit-cli/v2/pkg/apm/webrtc/third_party/abseil-cpp/absl/base"
	_ "github.com/livekit/livekit-cli/v2/pkg/apm/webrtc/third_party/abseil-cpp/absl/container"
	_ "github.com/livekit/livekit-cli/v2/pkg/apm/webrtc/third_party/abseil-cpp/absl/crc"
	_ "github.com/livekit/livekit-cli/v2/pkg/apm/webrtc/third_party/abseil-cpp/absl/debugging"
	_ "github.com/livekit/livekit-cli/v2/pkg/apm/webrtc/third_party/abseil-cpp/absl/flags"
	_ "github.com/livekit/livekit-cli/v2/pkg/apm/webrtc/third_party/abseil-cpp/absl/hash"
	_ "github.com/livekit/livekit-cli/v2/pkg/apm/webrtc/third_party/abseil-cpp/absl/log"
	_ "github.com/livekit/livekit-cli/v2/pkg/apm/webrtc/third_party/abseil-cpp/absl/numeric"
	_ "github.com/livekit/livekit-cli/v2/pkg/apm/webrtc/third_party/abseil-cpp/absl/profiling"
	_ "github.com/livekit/livekit-cli/v2/pkg/apm/webrtc/third_party/abseil-cpp/absl/random"
	_ "github.com/livekit/livekit-cli/v2/pkg/apm/webrtc/third_party/abseil-cpp/absl/status"
	_ "github.com/livekit/livekit-cli/v2/pkg/apm/webrtc/third_party/abseil-cpp/absl/strings"
	_ "github.com/livekit/livekit-cli/v2/pkg/apm/webrtc/third_party/abseil-cpp/absl/synchronization"
	_ "github.com/livekit/livekit-cli/v2/pkg/apm/webrtc/third_party/abseil-cpp/absl/time/src"
	_ "github.com/livekit/livekit-cli/v2/pkg/apm/webrtc/third_party/pffft/src"
	_ "github.com/livekit/livekit-cli/v2/pkg/apm/webrtc/third_party/rnnoise/src"
)
