// Copyright 2026 LiveKit, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package public is the CLI's client for the user-authenticated LiveKit Public
// API. It wraps the net/http client generated by oapi-codegen from the API's
// OpenAPI spec (pkg/public/oapi, regenerated via `go generate -tags oapigen`)
// behind the small domain surface the CLI needs, so callers don't depend on the
// generated types directly.
package public

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"strings"

	"github.com/livekit/livekit-cli/v2/pkg/public/oapi"
)

// DefaultBaseURL is the production base URL of the LiveKit Public API. Override
// it (e.g. to http://localhost:8000) for local development. The generated
// operation paths already include the /v1 prefix, so this is the host root.
const DefaultBaseURL = "https://beta-api.livekit.cloud"

// Client is the CLI's user-authenticated Public API client.
type Client struct {
	gen *oapi.ClientWithResponses
}

// Project is a project the authenticated user can access.
type Project struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Subdomain string `json:"subdomain,omitempty"`
}

// projectFrom maps a generated Project to the domain type.
func projectFrom(p *oapi.LivekitPublicapiProjectsV1Project) Project {
	if p == nil {
		return Project{}
	}
	return Project{ID: deref(p.Id), Name: deref(p.Name), Subdomain: deref(p.Subdomain)}
}

// New builds a Client for the Public API at baseURL, authenticating every
// request with the given user session token. If baseURL is empty, DefaultBaseURL
// is used. Extra client options may be passed (e.g. a custom http client).
func New(baseURL, token string, opts ...oapi.ClientOption) (*Client, error) {
	if baseURL == "" {
		baseURL = DefaultBaseURL
	}
	// Prepend the bearer-auth editor so callers' opts can still override it.
	opts = append([]oapi.ClientOption{oapi.WithRequestEditorFn(bearerAuth(token))}, opts...)
	gen, err := oapi.NewClientWithResponses(baseURL, opts...)
	if err != nil {
		return nil, err
	}
	return &Client{gen: gen}, nil
}

// bearerAuth returns a request editor that authorizes each request with the
// user session token.
func bearerAuth(token string) oapi.RequestEditorFn {
	return func(_ context.Context, req *http.Request) error {
		req.Header.Set("Authorization", "Bearer "+token)
		return nil
	}
}

// ListProjects returns the projects the authenticated user can access.
//
// NOTE: this returns only the first page; wire up PageInfo/cursor paging when a
// command needs the full set.
func (c *Client) ListProjects(ctx context.Context) ([]Project, error) {
	resp, err := c.gen.ProjectServiceListProjectsWithResponse(ctx, &oapi.ProjectServiceListProjectsParams{
		PagePageSize: ptr(int32(100)),
	})
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, responseError(resp.StatusCode(), resp.Body)
	}
	var items []oapi.LivekitPublicapiProjectsV1Project
	if resp.JSON200.Items != nil {
		items = *resp.JSON200.Items
	}
	projects := make([]Project, len(items))
	for i := range items {
		projects[i] = projectFrom(&items[i])
	}
	return projects, nil
}

// GetProject returns a single project by id.
func (c *Client) GetProject(ctx context.Context, projectID string) (*Project, error) {
	resp, err := c.gen.ProjectServiceGetProjectWithResponse(ctx, projectID)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, responseError(resp.StatusCode(), resp.Body)
	}
	p := projectFrom(resp.JSON200.Project)
	return &p, nil
}

// CreateProject creates a new project with the given name and returns it.
func (c *Client) CreateProject(ctx context.Context, name string) (*Project, error) {
	resp, err := c.gen.ProjectServiceCreateProjectWithResponse(ctx, oapi.ProjectServiceCreateProjectJSONRequestBody{
		Name: &name,
	})
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, responseError(resp.StatusCode(), resp.Body)
	}
	p := projectFrom(resp.JSON200.Project)
	return &p, nil
}

// UpdateProject updates a project's name and returns the updated project.
func (c *Client) UpdateProject(ctx context.Context, projectID, name string) (*Project, error) {
	resp, err := c.gen.ProjectServiceUpdateProjectWithResponse(ctx, projectID, oapi.ProjectServiceUpdateProjectJSONRequestBody{
		Name: &name,
	})
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, responseError(resp.StatusCode(), resp.Body)
	}
	p := projectFrom(resp.JSON200.Project)
	return &p, nil
}

// DeleteProject deletes a project by id.
func (c *Client) DeleteProject(ctx context.Context, projectID string) error {
	resp, err := c.gen.ProjectServiceDeleteProjectWithResponse(ctx, projectID)
	if err != nil {
		return err
	}
	if resp.StatusCode() != http.StatusOK {
		return responseError(resp.StatusCode(), resp.Body)
	}
	return nil
}

// APIError is a structured error from the Public API, carrying the HTTP status
// and the server's message. Callers can errors.As for it — notably via
// IsUnauthenticated / IsPermissionDenied.
type APIError struct {
	Status  int
	Message string
}

func (e *APIError) Error() string {
	if e.Message == "" {
		return fmt.Sprintf("unexpected response (HTTP %d)", e.Status)
	}
	return e.Message
}

// IsUnauthenticated reports whether err is an APIError signalling a missing or
// invalid session (HTTP 401), which the CLI surfaces as a prompt to re-run
// `lk cloud auth`.
func IsUnauthenticated(err error) bool {
	var apiErr *APIError
	return errors.As(err, &apiErr) && apiErr.Status == http.StatusUnauthorized
}

// IsPermissionDenied reports whether err is an APIError signalling that the
// authenticated account lacks access to the target project or action (HTTP 403).
func IsPermissionDenied(err error) bool {
	var apiErr *APIError
	return errors.As(err, &apiErr) && apiErr.Status == http.StatusForbidden
}

// responseError builds an APIError from a non-2xx response, preferring the
// gRPC-gateway error envelope ({"code","message","details"}) and falling back
// to the raw body.
func responseError(status int, body []byte) error {
	var env struct {
		Message string `json:"message"`
	}
	if err := json.Unmarshal(body, &env); err == nil && env.Message != "" {
		return &APIError{Status: status, Message: env.Message}
	}
	msg := strings.TrimSpace(string(body))
	if msg == "" {
		msg = http.StatusText(status)
	}
	return &APIError{Status: status, Message: fmt.Sprintf("unexpected response (HTTP %d): %s", status, msg)}
}

func ptr[T any](v T) *T { return &v }

func deref(s *string) string {
	if s == nil {
		return ""
	}
	return *s
}
