// Copyright 2026 LiveKit, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package public is the CLI's client for the user-authenticated LiveKit Public
// API. It is a thin wrapper over the net/http client generated by oapi-codegen
// from the API's OpenAPI spec (pkg/public/oapi, regenerated via
// `go generate -tags oapigen`): it adds bearer auth, unwraps the response
// envelopes, and classifies errors. Its methods return the generated types
// directly — the API is tightly versioned, so there is no separate domain model
// to keep in sync. The only value-mapping kept here is role int <-> name (see
// roles.go), which the wire format (a bare int32) genuinely lacks.
package public

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"strings"

	"github.com/livekit/livekit-cli/v2/pkg/public/oapi"
)

// DefaultBaseURL is the base URL of the LiveKit Public API. Override it (e.g. to
// http://localhost:8000) for local development. The generated operation paths
// already include the /v1 prefix, so this is the host root.
const DefaultBaseURL = "https://beta-api.livekit.cloud"

// Client is the CLI's user-authenticated Public API client.
type Client struct {
	gen *oapi.ClientWithResponses
}

// New builds a Client for the Public API at baseURL, authenticating every
// request with the given user session token. If baseURL is empty, DefaultBaseURL
// is used. Extra client options may be passed (e.g. a custom http client).
func New(baseURL, token string, opts ...oapi.ClientOption) (*Client, error) {
	if baseURL == "" {
		baseURL = DefaultBaseURL
	}
	// Prepend the bearer-auth editor so callers' opts can still override it.
	opts = append([]oapi.ClientOption{oapi.WithRequestEditorFn(bearerAuth(token))}, opts...)
	gen, err := oapi.NewClientWithResponses(baseURL, opts...)
	if err != nil {
		return nil, err
	}
	return &Client{gen: gen}, nil
}

// bearerAuth returns a request editor that authorizes each request with the
// user session token.
func bearerAuth(token string) oapi.RequestEditorFn {
	return func(_ context.Context, req *http.Request) error {
		req.Header.Set("Authorization", "Bearer "+token)
		return nil
	}
}

// ListProjects returns the projects the authenticated user can access.
//
// NOTE: this returns only the first page; wire up PageInfo/cursor paging when a
// command needs the full set.
func (c *Client) ListProjects(ctx context.Context) ([]oapi.LivekitPublicapiProjectsV1Project, error) {
	resp, err := c.gen.ProjectServiceListProjectsWithResponse(ctx, &oapi.ProjectServiceListProjectsParams{
		PagePageSize: ptr(int32(100)),
	})
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, responseError(resp.StatusCode(), resp.Body)
	}
	return items(resp.JSON200.Items), nil
}

// GetProject returns a single project by id.
func (c *Client) GetProject(ctx context.Context, projectID string) (*oapi.LivekitPublicapiProjectsV1Project, error) {
	resp, err := c.gen.ProjectServiceGetProjectWithResponse(ctx, projectID)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, responseError(resp.StatusCode(), resp.Body)
	}
	return requirePayload(resp.JSON200.Project, "project")
}

// CreateProject creates a new project with the given name and returns it.
func (c *Client) CreateProject(ctx context.Context, name string) (*oapi.LivekitPublicapiProjectsV1Project, error) {
	resp, err := c.gen.ProjectServiceCreateProjectWithResponse(ctx, oapi.ProjectServiceCreateProjectJSONRequestBody{
		Name: &name,
	})
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, responseError(resp.StatusCode(), resp.Body)
	}
	return requirePayload(resp.JSON200.Project, "project")
}

// UpdateProject updates a project's name and returns the updated project.
func (c *Client) UpdateProject(ctx context.Context, projectID, name string) (*oapi.LivekitPublicapiProjectsV1Project, error) {
	resp, err := c.gen.ProjectServiceUpdateProjectWithResponse(ctx, projectID, oapi.ProjectServiceUpdateProjectJSONRequestBody{
		Name: &name,
	})
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, responseError(resp.StatusCode(), resp.Body)
	}
	return requirePayload(resp.JSON200.Project, "project")
}

// DeleteProject deletes a project by id.
func (c *Client) DeleteProject(ctx context.Context, projectID string) error {
	resp, err := c.gen.ProjectServiceDeleteProjectWithResponse(ctx, projectID)
	if err != nil {
		return err
	}
	return okOrError(resp.StatusCode(), resp.Body)
}

// APIError is a structured error from the Public API, carrying the HTTP status
// and the server's message. Callers can errors.As for it — notably via
// IsUnauthenticated / IsPermissionDenied.
type APIError struct {
	Status  int
	Message string
}

func (e *APIError) Error() string {
	if e.Message == "" {
		return fmt.Sprintf("unexpected response (HTTP %d)", e.Status)
	}
	return e.Message
}

// IsUnauthenticated reports whether err is an APIError signalling a missing or
// invalid session (HTTP 401), which the CLI surfaces as a prompt to re-run
// `lk cloud auth`.
func IsUnauthenticated(err error) bool {
	var apiErr *APIError
	return errors.As(err, &apiErr) && apiErr.Status == http.StatusUnauthorized
}

// IsPermissionDenied reports whether err is an APIError signalling that the
// authenticated account lacks access to the target project or action (HTTP 403).
func IsPermissionDenied(err error) bool {
	var apiErr *APIError
	return errors.As(err, &apiErr) && apiErr.Status == http.StatusForbidden
}

// responseError builds an APIError from a non-2xx response, preferring the
// gRPC-gateway error envelope ({"code","message","details"}) and falling back
// to the raw body.
func responseError(status int, body []byte) error {
	var env struct {
		Message string `json:"message"`
	}
	if err := json.Unmarshal(body, &env); err == nil && env.Message != "" {
		return &APIError{Status: status, Message: env.Message}
	}
	msg := strings.TrimSpace(string(body))
	if msg == "" {
		msg = http.StatusText(status)
	}
	return &APIError{Status: status, Message: fmt.Sprintf("unexpected response (HTTP %d): %s", status, msg)}
}

// okOrError returns nil for a 200 response and a classified APIError otherwise.
// Used by delete/remove/cancel operations whose success payload is empty.
func okOrError(status int, body []byte) error {
	if status == http.StatusOK {
		return nil
	}
	return responseError(status, body)
}

// items dereferences an optional generated list pointer to a slice.
func items[T any](p *[]T) []T {
	if p == nil {
		return nil
	}
	return *p
}

// pageCursor returns the next-page cursor from a list response's PageInfo, or ""
// when there are no more pages.
func pageCursor(pi *oapi.LivekitPublicapiCommonV1PageInfo) string {
	if pi == nil || pi.NextCursor == nil {
		return ""
	}
	return *pi.NextCursor
}

// requirePayload guards a nested payload pointer from an otherwise-successful
// (200) response: the outer JSON200 can be non-nil while a nested field is nil,
// because a 200 with a missing/blank body still decodes (Go leaves absent fields
// at their zero value). Callers dereference the returned pointer, so surface a
// clear error rather than handing back a nil that panics downstream.
func requirePayload[T any](v *T, name string) (*T, error) {
	if v == nil {
		return nil, fmt.Errorf("unexpected response from server: missing %s", name)
	}
	return v, nil
}

func ptr[T any](v T) *T { return &v }
