// Copyright 2026 LiveKit, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// The typed client under ./oapi is generated by oapi-codegen from the LiveKit
// Public API's OpenAPI spec.
//
// # Source of truth
//
// The spec is served by the API itself at <base>/v1/openapi and fetched at
// generate time — no copy is kept in the repo. The base defaults to production
// (https://beta-api.livekit.cloud); override it for a local/staging server:
//
//	go generate -tags oapigen ./pkg/public/...                                       # prod
//	LK_PUBLIC_API_URL=http://localhost:8000 go generate -tags oapigen ./pkg/public/...
//
// The generate directive is gated behind the `oapigen` build tag so a plain
// `go generate ./...` never reaches the network; the committed ./oapi/oapi.gen.go
// keeps ordinary build/test offline and reproducible. The spec is OpenAPI 3.1
// (grpc-gateway); ./oapi/normalize.go collapses its union `type` arrays to
// 3.0-style types so oapi-codegen can consume it (see ./oapi/generate.sh).
package public
