// Copyright 2026 LiveKit, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package public is the CLI's client for the LiveKit Public API (the
// user-authenticated OpenAPI REST service), named to match public-api-server.
// The typed client under ./oapi is generated by oapi-codegen from an OpenAPI
// 3.1 spec — the same generator public-api-server uses for its server bindings
// (see ./oapi/generate.go and ./oapi/cfg.yaml).
//
// # Source of truth
//
// The authoritative spec is the published document served by the API itself,
// and no copy is kept in this repo. Regeneration fetches it directly (oapi-codegen
// loads http(s) URLs), defaulting to production; override for a local/staging
// server with LK_OPENAPI_SPEC_URL.
//
// The generate directive is gated behind the `oapigen` build tag so a plain
// `go generate ./...` never reaches the network — regenerate deliberately:
//
//	go generate -tags oapigen ./pkg/public/...                                              # prod
//	LK_OPENAPI_SPEC_URL=http://localhost:8080/openapi.yaml go generate -tags oapigen ./pkg/public/...
//
// The committed artifact is the generated ./oapi/oapi.gen.go, which is what
// keeps ordinary `go build`/`go test` reproducible and offline — only
// regeneration needs the network. The gated directive and the fetch live in
// ./oapi (generate.go, generate.sh, cfg.yaml).
//
// NOTE (temporary): the published spec does not yet describe the project
// endpoints (listProjects/getProject are 501-only, no success schema), so no
// Project type is generated. The client wraps those two endpoints by hand
// (see Client.ListProjects / GetProject in client.go) until the spec declares
// their schemas, at which point the hand-decoding can be replaced with the
// generated types.
package public
