name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/go/bin
            ~/.cache
          key: livekit-cli

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Download Go modules
        run: go mod download

      - uses: WillAbides/setup-go-faster@v1.7.0
        with:
          go-version: 1.18
      - name: Static Check
        uses: dominikh/staticcheck-action@v1.2.0
        with:
          version: "2022.1.2"
