on:
  workflow_dispatch:
    inputs:
      packages:
        description: "packages to bump"
        type: string
        required: true

jobs:
  bump:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nbsp/ilo@v2
        with:
          packages: ${{ github.event.inputs.packages }}
          prefix: v
